### ISSUE TITLE
Please explain use

### ISSUE THREAD

**Issue by reejit** [centralhardware/telegram_bot_alive_checker#1]
How can i request the app please give the format

**Comment by centralhardware** [comment]
about HTTP request

you need to send POST request with JSON in format

```json
{
  "username": "<bot username>"
}
```

if bot will react to the command / ping the response will be 200 almost immediately. otherwise request fail with timeout or send 400 (i use https://github.com/statping/statping, for monitoring and i set timeout for request)

by default bot start on 8080 port

if all ok you see something like

```log
INFO:root:<client>
INFO:aiohttp.access:192.168.176.1 [11/Jan/2021:18:15:14 +0000] "POST / HTTP/1.1" 200 168 "-" <client>

```

i see you try to deploy app to heroku. keep in mind that the application requires the telegram login code to be entered at the server start, this is required by telethon

**Comment by centralhardware** [comment]
I don’t know if it allows heroku, but I don’t think that it will be possible to refuse it
if you describe the problem in more detail, I can help more specifically

**Comment by reejit** [comment]
Yes it allows heroku and i tried it too i logged successfully in my account i think i should try python3 🤔

**Comment by reejit** [comment]
Accidentally closed

**Comment by reejit** [comment]
Please convert it to GET instead of POST

**Comment by centralhardware** [comment]
i add GET endpoint handling by https://github.com/centralhardware/telegram_bot_alive_checker/commit/c9ad1eb98c97de0ee3874e9a2e48326834b0a609

example:

```sh
curl "localhost:8080?username=<bot username>" 
```

**Comment by reejit** [comment]
Telethon repeatly asks for login code even if i logged in successfully 


And it doesn't work in GET request

**Comment by reejit** [comment]
I tried this https://example.com/?username=@testbot

**Comment by centralhardware** [comment]
You need pass username without @

**Comment by reejit** [comment]
But it gives Error app crashed

**Comment by reejit** [comment]
And auth problem?

**Comment by reejit** [comment]
Why did you block me i wanted to ask you the solution

**Comment by centralhardware** [comment]
> Why did you block me i wanted to ask you the solution

i didn't block you anywhere

**Comment by reejit** [comment]
> > Why did you block me i wanted to ask you the solution
> 
> i didn't block you anywhere

![Screenshot_20210113_181522](https://user-images.githubusercontent.com/70316178/104454107-5c49e200-55cb-11eb-8215-75d545f988a1.png)

**Comment by reejit** [comment]
> But it gives Error app crashed

And this @centralhardware

**Comment by reejit** [comment]
@centralhardware

**Comment by centralhardware** [comment]
Please profilde more information about your problem
